Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8096"
    vb.cpus = 4
  end

  nodes = {
    "master" => "192.168.56.30",
    "worker" => "192.168.56.31"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = name 
      node.vm.network "private_network", ip: ip
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y curl wget vim net-tools
      SHELL
    end
  end
end